# Generated by Django 5.0.8 on 2025-05-17 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('Buy', 'Buy'), ('Sell', 'Sell')], max_length=10)),
                ('stock_symbol', models.CharField(choices=[('GHL', 'GHL'), ('BHL', 'BHL'), ('CHL', 'CHL'), ('AKJCL', 'AKJCL')], max_length=10)),
                ('quantity', models.IntegerField()),
                ('date', models.DateField(blank=True, null=True)),
                ('type', models.CharField(choices=[('Secondary', 'Secondary'), ('IPO', 'IPO'), ('FPO', 'FPO'), ('Bonus', 'Bonus'), ('Right', 'Right'), ('Auction', 'Auction')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dp_charge', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('capital_gain_tax', models.DecimalField(choices=[(0, 0), (5, 5), (7.5, 7.5), (10, 10)], decimal_places=1, max_digits=10)),
                ('user', models.CharField(blank=True, default='aayush', max_length=16, null=True)),
            ],
        ),
    ]
