# Generated by Django 5.0.8 on 2025-05-17 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='capital_gain_tax',
            field=models.FloatField(choices=[(0.0, '0%'), (5.0, '5%'), (7.5, '7.5%'), (10.0, '10%')]),
        ),
    ]
